<?php if ($config = $this->getBannerConfig()): ?>
<div class="slidein-banner collapsed">
    <div class="banner-content">
        <?php echo Mage::getSingleton('core/layout')
            ->createBlock('cms/block')
            ->setBlockId($config['block_id'])
            ->toHtml();
        ?>
    </div>
    <div class="banner-handle">
        <a class="title" href="#" onclick="openSlideInBanner();">
            <?php echo $this->escapeHtml($config['title']); ?>
        </a>
    </div>
</div>
<?php endif; ?>
